# Generated by Django 5.0.6 on 2026-06-19 00:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.CharField(default='小区物业服务中心', max_length=50, verbose_name='收款人'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='建筑面积'),
        ),
    ]
